apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: oarage-server
spec:
  selector:
    matchLabels:
      app: oarage
      tier: oarage-server
  replicas: 3
  template:
    metadata:
      labels:
        app: oarage
        tier: oarage-server
    spec:
      containers:
      - name: oarage-server
        image: oarage/oarage
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 6881
---
apiVersion: v1
kind: Service
metadata:
  name: oarage-server
spec:
  selector:
    app: oarage
    tier: oarage-server
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oarage-server
spec:
  rules:
  - host: oarage.local
    http:
      paths:
      - path: /
        backend:
          serviceName: oarage-server
          servicePort: http